FROM php:PHPFPM_VERSION
MAINTAINER Pablo Baenas <contacto@pablobaenas.com>

RUN apt-get update && apt-get install -y \
  cron \
  git \
  gzip \
  libbz2-dev \
  libfreetype6-dev \
  libicu-dev \
  libjpeg62-turbo-dev \
  libmcrypt-dev \
  libpng-dev \
  libsodium-dev \
  libssh2-1-dev \
  libxslt1-dev \
  libzip-dev \
  lsof \
  default-mysql-client \
  vim \
  zip PHPFPM_DOCKER_INSTALL_PHP74


RUN docker-php-ext-configure PHPFPM_DOCKER_GD_COMMAND

#RUN docker-php-ext-install bcmath bz2 calendar
#RUN docker-php-ext-install exif
#RUN docker-php-ext-install gd
#RUN docker-php-ext-install gettext
#RUN docker-php-ext-install intl
#RUN docker-php-ext-install mbstring
#RUN docker-php-ext-install mysqli
#RUN docker-php-ext-install opcache
#RUN docker-php-ext-install pcntl
#RUN docker-php-ext-install pdo_mysql
#RUN docker-php-ext-install soap
#RUN docker-php-ext-install sockets
#RUN docker-php-ext-install sodium
#RUN docker-php-ext-install sysvmsg sysvsem sysvshm
#RUN docker-php-ext-install xsl zip

RUN docker-php-ext-install \
  bcmath \
  bz2 \
  calendar \
  exif \
  gd \
  gettext \
  intl \
  mbstring \
  mysqli \
  opcache \
  pcntl \
  pdo_mysql \
  soap \
  sodium \
  sockets \
  sysvmsg \
  sysvsem \
  sysvshm \
  xsl \
  zip

RUN pecl channel-update pecl.php.net \
  && pecl install xdebug

RUN docker-php-ext-enable xdebug \
  && sed -i -e 's/^zend_extension/\;zend_extension/g' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.client_host = host.docker.internal" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

RUN groupadd -g 1000 app \
 && useradd -g 1000 -u 1000 -d /var/www -s /bin/bash app

RUN curl -sSLO https://github.com/mailhog/mhsendmail/releases/download/v0.2.0/mhsendmail_linux_amd64 \
  && chmod +x mhsendmail_linux_amd64 \
  && mv mhsendmail_linux_amd64 /usr/local/bin/mhsendmail

COPY --from=composer:COMPOSER_VERSION /usr/bin/composer /usr/local/bin/composer

RUN printf '* *\t* * *\tapp\t%s/usr/local/bin/php /var/www/html/update/cron.php\n' >> /etc/crontab \
  && printf '* *\t* * *\tapp\t%s/usr/local/bin/php /var/www/html/bin/magento cron:run\n' >> /etc/crontab \
  && printf '* *\t* * *\tapp\t%s/usr/local/bin/php /var/www/html/bin/magento setup:cron:run\n#\n' >> /etc/crontab

COPY conf/php/www.conf /usr/local/etc/php-fpm.d/
COPY conf/php/php.ini /usr/local/etc/php/
COPY conf/php/php-fpm.conf /usr/local/etc/
# COPY bin/cronstart /usr/local/bin/

RUN mkdir -p /etc/nginx/html /var/www/html /sock \
  && chown -R app:app /etc/nginx /var/www /usr/local/etc/php/conf.d /sock

USER app:app

VOLUME /var/www

WORKDIR /var/www/html

EXPOSE 9001
