  elasticsearch_PROJECTNAME_m2:
    image: elasticsearch:ELASTICSEARCH_VERSION
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
