  app_PROJECTNAME_m2:
    build:
      context: .
      dockerfile: 'conf/docker/app/Dockerfile'
    ports:
      - "80:8000"
      - "443:8443"
    links:
      - db_PROJECTNAME_m2
      - phpfpm_PROJECTNAME_m2
      LINK_RABBITMQ
    volumes: &appvolumes
#      - ./src:/var/www/html:delegated
#      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
      - appdata:/var/www/html
#      - ./src/app:/var/www/html/app:delegated
#      - ./src/vendor:/var/www/html/vendor:delegated
      - sockdata:/sock
      - ssldata:/etc/nginx/certs
